"""working on seat table

Revision ID: 7a9dff238c2e
Revises: ec46024eb0e0
Create Date: 2024-08-13 18:08:09.980388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9dff238c2e'
down_revision = 'ec46024eb0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('seat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
