"""changed driver_id column

Revision ID: 558c44d8029b
Revises: 7a9dff238c2e
Create Date: 2024-08-16 14:25:14.570988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558c44d8029b'
down_revision = '7a9dff238c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
