"""added selected_seats

Revision ID: 7a672bf698da
Revises: f2fe567b29cc
Create Date: 2024-08-13 13:11:42.973467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a672bf698da'
down_revision = 'f2fe567b29cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_seats', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('selected_seats')

    # ### end Alembic commands ###
