"""Add role column to customers

Revision ID: 9c2771094071
Revises: 7facfec065ed
Create Date: 2024-08-07 20:26:29.419018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2771094071'
down_revision = '7facfec065ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
