"""added seat table

Revision ID: ec46024eb0e0
Revises: 7c8d9cb9d180
Create Date: 2024-08-13 16:43:46.172800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec46024eb0e0'
down_revision = '7c8d9cb9d180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        # Allow seat column to be nullable initially
        batch_op.add_column(sa.Column('seat', sa.String(), nullable=True))

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.alter_column('bus_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # After the upgrade, you can run a script to set default values for existing records (if needed).
    # Example: Set default value for the seat column in existing bookings.
    op.execute("UPDATE bookings SET seat = 'default_seat_value' WHERE seat IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.alter_column('bus_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('seat')

    # ### end Alembic commands ###
